import { useMemo, useState } from "react";
import { Activity, BarChart3, CalendarDays, ChevronLeft, Database, ExternalLink, ShieldCheck, Trophy, Wifi, Target, Clock3, MapPin } from "lucide-react";
import { trpc } from "./lib/trpc";
import { adaptiveRefreshMs, formatIraqDate, sortRealMadridFirst } from "@shared/footballDomain";

type Match = any;
const competitions = [
  { id: "laliga", label: "الدوري الإسباني" },
  { id: "championsLeague", label: "دوري الأبطال" },
  { id: "copaDelRey", label: "كأس الملك" },
  { id: "superCup", label: "السوبر الإسباني" },
] as const;

function formatDate(value: unknown, withTime = false) { return formatIraqDate(value as any, withTime); }
function stateLabel(state: string | undefined) { return ({ LIVE:"مباشر", FRESH:"محدث", VERIFIED:"موثوق", STALE:"قديم نسبيًا", FALLBACK:"مصدر احتياطي", UNAVAILABLE:"غير متاح" } as any)[state || ""] || "غير معروف"; }
function initials(name: string) { return (name || "RM").split(" ").slice(0,2).map(x=>x[0]).join("").toUpperCase(); }
function normalizeMatches(data: any): Match[] { return data?.matches || []; }
function teamName(team: any, fallback = "—") { return typeof team === "string" ? team : team?.name || team?.displayName || fallback; }
const STADIUM_IMAGES: Record<string,string> = { bernabeu:"/stadiums/santiago-bernabeu.jpg", martinez:"/stadiums/manuel-martinez-valero.jpg", metropolitano:"/stadiums/metropolitano.jpg", ceramica:"/stadiums/la-ceramica.jpg", default:"/stadiums/default.jpg" };
function stadiumKey(match:any) { const s=`${match?.venue||""} ${teamName(match?.homeTeam,"")}`.toLowerCase(); if(/bernabeu|santiago|real madrid/.test(s))return "bernabeu"; if(/martinez|valero|elche/.test(s))return "martinez"; if(/metropolitano|wanda|atletico/.test(s))return "metropolitano"; if(/ceramica|villarreal/.test(s))return "ceramica"; return "default"; }
function StadiumBackground({match,children,className=""}:any){const [failed,setFailed]=useState(false);const k=stadiumKey(match);return <div className={`stadium-bg stadium-${k} ${className}`} style={!failed?{backgroundImage:`linear-gradient(90deg,rgba(4,12,24,.94),rgba(7,18,34,.68),rgba(4,12,24,.94)),url(${STADIUM_IMAGES[k]})`}:undefined}><img className="stadium-preload" src={STADIUM_IMAGES[k]} onError={()=>setFailed(true)} alt=""/>{children}</div>}
function TeamBadge({name,logo,size="md"}:any){const [failed,setFailed]=useState(false);return <div className={`team-badge ${size}`}>{logo&&!failed?<img src={logo} alt={name} onError={()=>setFailed(true)}/>:<span>{initials(name)}</span>}</div>}

function App() {
  const [view, setView] = useState<"home"|"matches"|"competitions"|"analytics"|"sources"|"match">("home");
  const [selected, setSelected] = useState<Match | null>(null);
  const matchesQuery = trpc.matches.list.useQuery({ daysBefore: 365, daysAfter: 180 }, { staleTime: 15_000, refetchInterval: query => { const list = (query.state.data as any)?.matches || []; const liveMatch = list.find((m:any) => /live|halftime|second_half|extra|penalty/i.test(String(m.status))); return liveMatch ? 15_000 : 60_000; } });
  const statusQuery = trpc.matches.health.useQuery(undefined, { refetchInterval: 60_000 });
  const matches = useMemo(() => sortRealMadridFirst(normalizeMatches(matchesQuery.data)), [matchesQuery.data]);
  const live = matches.find(m => String(m.status).toLowerCase().includes("live") || m.dataState === "LIVE");
  const upcoming = matches.filter(m => String(m.status).toLowerCase().includes("scheduled") || String(m.status).toLowerCase().includes("pre"))[0] || matches[0];
  const recent = matches.filter(m => String(m.status).toLowerCase().includes("completed") || String(m.status).toLowerCase().includes("finished") || String(m.status).toLowerCase().includes("post")).slice(-5).reverse();
  const nav = (v: typeof view) => { setView(v); window.scrollTo({ top:0, behavior:"smooth" }); };
  return <div className="shell" dir="rtl">
    <header className="topbar"><div className="container nav">
      <button className="brand" onClick={()=>nav("home")} style={{background:"none",border:0}}><span className="crest">RM</span><span>IBRA-LIVE-RMA<small>مركز ريال مدريد الذكي</small></span></button>
      <nav className="navlinks">{[["home","الرئيسية"],["matches","المباريات"],["competitions","البطولات"],["analytics","التحليلات"],["sources","مصادر البيانات"]].map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>nav(id as any)}>{label}</button>)}</nav>
      <div className="live-pill"><i className="dot"/> {live ? "مباراة مباشرة" : "المركز يعمل"}</div>
    </div></header>
    <main className="container">
      {view === "home" && <Home matches={matches} live={live} upcoming={upcoming} recent={recent} status={statusQuery.data} loading={matchesQuery.isLoading} onOpen={(m: Match)=>{setSelected(m);nav("match")}} onView={nav} />}
      {view === "matches" && <MatchesPage matches={matches} loading={matchesQuery.isLoading} onOpen={(m: Match)=>{setSelected(m);nav("match")}} />}
      {view === "competitions" && <CompetitionsPage matches={matches} onOpen={(m: Match)=>{setSelected(m);nav("match")}} />}
      {view === "analytics" && <Analytics matches={matches} />}
      {view === "sources" && <Sources data={statusQuery.data} matchesData={matchesQuery.data} />}
      {view === "match" && <MatchCenter match={selected || upcoming} onBack={()=>nav("home")} />}
    </main>
    <footer className="container footer"><strong>IBRA-LIVE-RMA</strong><span>بيانات مفتوحة • تحديث مستمر • عرض شفاف للمصادر</span><span>آخر فحص: {formatDate(new Date(), true)}</span></footer>
  </div>;
}

function Home({matches, live, upcoming, recent, status, loading, onOpen, onView}: any) { const freshness = status?.freshness; return <>
  <section className="hero"><div><div className="eyebrow">Real Madrid match intelligence</div><h1>كل ما يخص ريال مدريد، في لحظته.</h1><p>مركز موحد للمباريات والنتائج والتحليلات، مع توضيح مصدر البيانات وحداثتها بدل عرض أرقام بلا سياق.</p></div><div className="hero-meta"><span className="source-pill"><ShieldCheck size={14}/> {stateLabel(freshness?.state || "VERIFIED")}</span><span className="source-pill"><Wifi size={14}/> ESPN + TheSportsDB</span></div></section>
  <section className="grid grid-4"><Kpi icon={<CalendarDays/>} label="المباريات القادمة" value={matches.filter((m:any)=>String(m.status).toLowerCase().includes("scheduled") || String(m.status).toLowerCase().includes("pre")).length} note="ضمن نطاق 180 يومًا"/><Kpi icon={<Activity/>} label="آخر حالة" value={live ? "مباشر" : "جاهز"} note={live ? "تحديث كل 15 ثانية" : "لا توجد مباراة مباشرة"}/><Kpi icon={<Database/>} label="حالة المصدر" value={stateLabel(matches?.[0]?.dataState)} note={matches?.[0]?.source || "بانتظار البيانات"}/><Kpi icon={<Trophy/>} label="إجمالي السجل" value={matches.length} note="مباراة موحدة"/></section>
  <section className="section grid grid-main"><div><div className="section-head"><div><h2 className="section-title">المشهد الرئيسي</h2><p className="section-sub">المباراة القادمة أو الحالية</p></div><button className="navlinks active" onClick={()=>onView("matches")}>كل المباريات <ChevronLeft size={15}/></button></div>{loading ? <Loading/> : <Featured match={live || upcoming} live={!!live} onOpen={onOpen}/>}</div><div><div className="section-head"><div><h2 className="section-title">آخر النتائج</h2><p className="section-sub">اسم البطولة أسفل كل مباراة</p></div></div><div className="list">{recent.length ? recent.map((m:any,i:number)=><Fixture key={m.providerId || i} match={m} onClick={()=>onOpen(m)}/>) : <div className="card empty">لا توجد نتائج متاحة بعد</div>}</div></div></section>
  <section className="section grid grid-2"><div className="card panel"><h3 className="panel-title">ماذا يحدث الآن؟</h3><div className="list"><InfoRow label="المصدر الأساسي" value="ESPN public feed"/><InfoRow label="المصدر الاحتياطي" value="TheSportsDB"/><InfoRow label="التحديث" value={freshness?.updatedAt ? formatDate(freshness.updatedAt,true) : "عند الطلب"}/></div></div><div className="card panel"><h3 className="panel-title">مبدأ الثقة</h3><p style={{color:"#a9bad3",lineHeight:1.9,fontSize:14}}>لا نعرض نتيجة أو حالة دون ربطها بمصدر وزمن تحديث. عند تعطل المصدر، نوضح ذلك ونستخدم النسخة المحفوظة بدل إخفاء المشكلة.</p><button className="navlinks active" onClick={()=>onView("sources")}>استكشف المصادر <ExternalLink size={14}/></button></div></section>
</> }
function Kpi({icon,label,value,note}:any){return <div className="card kpi"><div style={{color:"#d7ad54"}}>{icon}</div><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div><div className="kpi-note">{note}</div></div>}
function InfoRow({label,value}:any){return <div style={{display:"flex",justifyContent:"space-between",gap:10,color:"#9eb0ca",fontSize:13}}><span>{label}</span><strong style={{color:"#eef2ff",fontSize:12}}>{value}</strong></div>}
function Loading(){return <div className="card loading"><div><div className="spinner"/><p>جارٍ مزامنة البيانات...</p></div></div>}
function Featured({match,live,onOpen}:any){if(!match)return <div className="card empty">لا توجد مباراة ضمن النطاق الحالي</div>; const h=teamName(match.homeTeam,"Real Madrid"),a=teamName(match.awayTeam,"Opponent");return <StadiumBackground match={match} className="card match-card featured"><div className="match-top"><span>{match.competitionLabel||match.competition||"مباراة"}</span><span className={live?"live-pill":"source-pill"}>{live&&<i className="dot"/>}{live?"مباشر":stateLabel(match.dataState)}</span></div><div className="teams"><div><TeamBadge name={h} logo={match.homeLogo}/><div className="team-name">{h}</div></div><div><div className="score">{match.homeScore!=null?`${match.homeScore} — ${match.awayScore}`:"VS"}</div><div className="versus">{live?"الآن":formatDate(match.startTimeUtc,true)}</div></div><div><TeamBadge name={a} logo={match.awayLogo}/><div className="team-name">{a}</div></div></div><div className="match-meta"><span><Trophy size={14}/>{match.competitionLabel||match.competition}</span><span><CalendarDays size={14}/>{formatDate(match.startTimeUtc,true)}</span><span><MapPin size={14}/>{match.venue||"الملعب غير منشور"}</span><span><ShieldCheck size={14}/>{stateLabel(match.dataState)}</span></div><div className="match-footer"><span>{match.source||"مصدر مفتوح"}</span><button className="navlinks active" onClick={()=>onOpen(match)}>مركز المباراة <ChevronLeft size={14}/></button></div></StadiumBackground>}
function Fixture({match,onClick}:any){const h=teamName(match.homeTeam,"Real Madrid"),a=teamName(match.awayTeam,"Opponent");return <button className="card fixture" onClick={onClick}><div className="fixture-date">{formatDate(match.startTimeUtc)}<br/><span className="status">{stateLabel(match.dataState)}</span></div><div className="fixture-teams"><div className="fixture-team"><TeamBadge name={h} logo={match.homeLogo} size="sm"/><strong>{h}</strong></div><span>×</span><div className="fixture-team"><TeamBadge name={a} logo={match.awayLogo} size="sm"/><strong>{a}</strong></div><small>{match.competitionLabel||match.competition||"مباراة"}</small></div><div className="fixture-score">{match.homeScore!=null?`${match.homeScore}-${match.awayScore}`:"—"}</div></button>}

function MatchesPage({matches,loading,onOpen}:any){const [tab,setTab]=useState<"upcoming"|"finished">("upcoming");const now=Date.now();const isFinished=(m:any)=>m.homeScore!=null&&m.awayScore!=null||/completed|finished|post|cancel/i.test(String(m.status));const upcoming=matches.filter((m:any)=>!isFinished(m)&&(m.startTimeUtc||0)>=now);const finished=matches.filter((m:any)=>isFinished(m)||(m.startTimeUtc||0)<now);const visible=tab==="upcoming"?upcoming:finished;return <><section className="hero"><div><div className="eyebrow">Fixture intelligence</div><h1>المباريات، بلا ضوضاء.</h1><p>سجل كامل للمباريات المنتهية، وجدول متتابع للمباريات القادمة خلال 180 يومًا.</p></div></section><div className="detail-tabs card match-tabs"><button className={tab==="upcoming"?"active":""} onClick={()=>setTab("upcoming")}>المباريات القادمة <b>{upcoming.length}</b></button><button className={tab==="finished"?"active":""} onClick={()=>setTab("finished")}>المباريات المنتهية <b>{finished.length}</b></button></div><section className="section">{loading?<Loading/>:visible.length?<div className="list">{visible.map((m:any,i:number)=><Fixture key={m.providerId||i} match={m} onClick={()=>onOpen(m)}/>)}</div>:<div className="card empty">لا توجد مباريات ضمن هذا التبويب حاليًا</div>}</section></>}
function CompetitionsPage({matches,onOpen}:any){
  const [competition,setCompetition]=useState<any>("laliga");
  const snapshot=trpc.matches.snapshot.useQuery({competition},{staleTime:10*60_000,gcTime:30*60_000,refetchInterval:10*60_000});
  const competitionMatches=matches.filter((m:any)=>m.competition===competition);
  const rows=snapshot.data?.standings||[]; const scorers=snapshot.data?.scorers||[];
  return <><section className="hero"><div><div className="eyebrow">Competition intelligence</div><h1>البطولات في شاشة واحدة.</h1><p>ترتيب وهدافون ومباريات كل بطولة مدعومة، مع حالة المصدر ووقت التحديث.</p></div></section>
    <div className="detail-tabs card">{competitions.map(c=><button className={competition===c.id?"active":""} onClick={()=>setCompetition(c.id)} key={c.id}>{c.label}</button>)}</div>
    <section className="section grid grid-main"><div className="card panel"><div className="section-head"><div><h2 className="section-title">الترتيب</h2><p className="section-sub">{snapshot.data?.standingsStatus||"جارٍ التحقق"} • {snapshot.data?.source||"ESPN"}</p></div><Trophy size={20} color="#d7ad54"/></div>{rows.length?<table className="table"><thead><tr><th>#</th><th>الفريق</th><th>لعب</th><th>نقاط</th><th>فارق</th><th>النموذج</th></tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={r.team?.id||i}><td className="rank">{r.rank||i+1}</td><td><span className="table-team"><TeamBadge name={teamName(r.team,r.teamName||"—")} logo={r.logo||r.team?.logo} size="sm"/><strong>{teamName(r.team,r.teamName||"—")}</strong></span></td><td>{r.played??"—"}</td><td><strong>{r.points??"—"}</strong></td><td>{r.goalDifference??"—"}</td><td style={{color:r.team?.name?.toLowerCase().includes("real madrid")?"#d7ad54":"#9eb0ca"}}>{r.form||"—"}</td></tr>)}</tbody></table>:<div className="empty">لا يوجد ترتيب منشور لهذه البطولة حاليًا. {snapshot.data?.standingsStatus||""}</div>}</div>
      <div className="list"><div className="card panel"><div className="section-head"><h2 className="panel-title">الهدافون</h2><Target size={19} color="#d7ad54"/></div>{scorers.length?scorers.slice(0,8).map((s:any,i:number)=><div className="fixture" style={{padding:"10px 0"}} key={i}><div className="rank">{i+1}</div><div className="fixture-teams" style={{textAlign:"right"}}><strong>{s.player||s.playerName||s.player?.name||"لاعب"}</strong><span className="table-team-inline"><TeamBadge name={s.team||s.teamName||s.team?.name||"—"} logo={s.teamLogo||s.logo} size="xs"/>{s.team||s.teamName||s.team?.name||"—"}</span></div><div className="fixture-score">{s.goals??"—"}</div></div>):<div className="empty">لا توجد قائمة هدافين متاحة</div>}</div><div className="card panel"><h2 className="panel-title">مباريات ريال مدريد في البطولة</h2>{competitionMatches.length?competitionMatches.slice(0,6).map((m:any,i:number)=><Fixture key={i} match={m} onClick={()=>onOpen(m)}/>):<div className="empty">لا توجد مباريات ضمن النطاق الحالي</div>}</div></div></section></>;
}
function Analytics({matches}:any){const finished=matches.filter((m:any)=>m.homeScore!=null&&m.awayScore!=null&&m.isRealMadrid);const goals=finished.reduce((s:number,m:any)=>{const home=teamName(m.homeTeam,"").toLowerCase().includes("real madrid");return s+(home?m.homeScore||0:m.awayScore||0)},0);return <><section className="hero"><div><div className="eyebrow">Performance lab</div><h1>الأرقام تحكي القصة.</h1><p>ملخص تحليلي أولي فوق البيانات الموحدة، قابل للتوسع بإحصائيات اللاعبين والأحداث والزخم.</p></div></section><section className="grid grid-4"><Kpi icon={<BarChart3/>} label="مباريات مكتملة" value={finished.length} note="بيانات لها نتيجة"/><Kpi icon={<Trophy/>} label="الأهداف المسجلة" value={goals} note="أهداف ريال مدريد فقط"/><Kpi icon={<Activity/>} label="متوسط الأهداف" value={finished.length?(goals/finished.length).toFixed(1):"—"} note="لكل مباراة لريال مدريد"/><Kpi icon={<ShieldCheck/>} label="جودة البيانات" value={matches.length?"مرئية":"—"} note="مع حالة المصدر"/></section><section className="section grid grid-main"><div className="card panel"><h3 className="panel-title">توزيع النتائج الأخيرة</h3>{finished.slice(0,8).map((m:any,i:number)=><div key={i} style={{marginBottom:16}}><InfoRow label={`${m.homeTeam?.name||m.homeTeam||"Home"} × ${m.awayTeam?.name||m.awayTeam||"Away"}`} value={`${m.homeScore ?? "—"} — ${m.awayScore ?? "—"}`}/><div className="bar" style={{marginTop:7}}><i style={{width:`${Math.min(100,40+((m.homeScore||0)+(m.awayScore||0))*10)}%`}}/></div></div>)}</div><div className="card panel"><h3 className="panel-title">قراءة سريعة</h3><p style={{lineHeight:2,color:"#a9bad3",fontSize:14}}>هذه الطبقة مصممة لعرض مؤشرات مفهومة أولًا، ثم تعميقها لاحقًا بإحصائيات التسديد والاستحواذ والتمرير والتشكيلات عند توفرها من المصدر.</p></div></section></>}
function Sources({data,matchesData}:any){const sources=matchesData?.sources || data?.sources || [];return <><section className="hero"><div><div className="eyebrow">Trust center</div><h1>نعرض البيانات، ونشرحها.</h1><p>كل رقم مرتبط بحالة ومصدر ووقت تحديث. عند استخدام نسخة محفوظة، يظهر ذلك صراحة.</p></div></section><section className="grid grid-3"><div className="card panel"><h3 className="panel-title">الحالة الحالية</h3><InfoRow label="البيانات" value={stateLabel(matchesData?.dataState || data?.freshness?.state)}/><InfoRow label="المصدر" value={matchesData?.source || data?.freshness?.source || "—"}/><InfoRow label="آخر تحديث" value={formatDate(matchesData?.sourceUpdatedAt || data?.freshness?.updatedAt,true)}/></div>{(sources.length?sources:[{provider:"ESPN",status:"operational",latencyMs:null},{provider:"TheSportsDB",status:"standby",latencyMs:null}]).map((s:any,i:number)=><div className="card panel" key={s.provider||i}><div className="source-pill" style={{marginBottom:15}}><ShieldCheck size={14}/> {s.status || "operational"}</div><h3 className="panel-title">{s.provider || s.source || "Provider"}</h3><InfoRow label="الزمن" value={s.latencyMs ? `${s.latencyMs}ms` : "متاح"}/><InfoRow label="الدور" value={i===0?"أساسي":"احتياطي"}/></div>)}</section></>}
function MatchCenter({match,onBack}:any){const detail=trpc.matches.detail.useQuery(match?{matchId:String(match.providerId||match.id),competition:match.competition||"laliga"}:({matchId:"",competition:"laliga"} as any),{enabled:!!match,refetchInterval:match?.status==="live"?15000:false});const detailData:any=detail.data;const [tab,setTab]=useState("overview");const h=match?.homeTeam?.name||match?.homeTeam||match?.home?.name||"Real Madrid";const a=match?.awayTeam?.name||match?.awayTeam||match?.away?.name||"Opponent";const h2h=trpc.matches.h2h.useQuery({teamA:h,teamB:a},{enabled:!!match,staleTime:300000});const lines=detailData?.lineups||[];const players=detailData?.playerStats||[];return <><button className="navlinks active" onClick={onBack} style={{marginTop:28}}><ChevronLeft size={15}/> العودة</button><section className="section card detail-hero"><div className="eyebrow">{match?.competitionLabel||match?.competition||"Match center"}</div><div className="teams"><div><div className="team-logo">{initials(h)}</div><div className="team-name">{h}</div></div><div><div className="score">{match?.homeScore!=null?`${match.homeScore} — ${match.awayScore}`:"VS"}</div><div className="versus">{formatDate(match?.startTimeUtc,true)}</div></div><div><div className="team-logo">{initials(a)}</div><div className="team-name">{a}</div></div></div><span className="source-pill"><ShieldCheck size={14}/> {stateLabel(match?.dataState)} • {match?.source||"مصدر مفتوح"}</span></section><div className="card"><div className="detail-tabs">{[["overview","الملخص"],["timeline","الخط الزمني"],["stats","الإحصائيات"],["lineups","التشكيلات"],["players","اللاعبون"],["h2h","H2H"],["sources","المصادر"]].map(([id,l])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{l}</button>)}</div><div className="panel">{detail.isLoading?<Loading/>:tab==="overview"?<div className="grid grid-3"><div><h3 className="panel-title">الحالة</h3><p className="kpi-value">{stateLabel(match?.dataState)}</p></div><div><h3 className="panel-title">الملعب والحكم</h3><p style={{color:"#a9bad3"}}>{detailData?.header?.venue||"غير منشور"}<br/>{detailData?.header?.referee||"الحكم غير منشور"}</p></div><div><h3 className="panel-title">آخر تحديث</h3><p style={{color:"#a9bad3"}}>{formatDate(match?.sourceUpdatedAt,true)}</p></div></div>:tab==="timeline"?<Timeline events={detailData?.incidents||match?.events||[]}/>:tab==="stats"?<Stats stats={detailData?.stats||match?.stats||{}}/>:tab==="lineups"?<Lineups lines={lines}/>:tab==="players"?<PlayerStats players={players}/>:tab==="h2h"?<H2H data={h2h.data}/>:<div className="empty">المصدر: {match?.source||"غير متاح"}<br/>الحالة: {stateLabel(match?.dataState)}</div>}</div></div></>}
function Lineups({lines}:any){return lines?.length?<div className="grid grid-2">{lines.map((team:any,i:number)=><div className="card panel" key={i}><h3 className="panel-title">{team.team} {team.formation&&<span className="section-sub">{team.formation}</span>}</h3>{(team.players||[]).slice(0,18).map((p:any,j:number)=><InfoRow key={j} label={`${p.jersey||""} ${p.player||p.name||"لاعب"}`} value={p.starter?"أساسي":"بديل"}/>)}</div>)}</div>:<div className="empty">لا توجد تشكيلات منشورة من المصدر حتى الآن</div>}
function PlayerStats({players}:any){return players?.length?<table className="table"><thead><tr><th>اللاعب</th><th>الفريق</th><th>الدور</th><th>الدقائق</th><th>إحصائيات</th></tr></thead><tbody>{players.map((p:any,i:number)=><tr key={i}><td><strong>{p.player||p.name||"—"}</strong></td><td>{p.team||"—"}</td><td>{p.starter?"أساسي":"بديل"}</td><td>{p.minutes??"—"}</td><td>{Object.entries(p.stats||{}).slice(0,3).map(([k,v])=><span key={k} style={{marginLeft:8,color:"#9eb0ca"}}>{k}: {String(v)}</span>)}</td></tr>)}</tbody></table>:<div className="empty">إحصائيات اللاعبين غير متاحة لهذه المباراة</div>}
function H2H({data}:any){return data?.matches?.length?<><div className="grid grid-3" style={{marginBottom:18}}><Kpi icon={<Trophy/>} label="مواجهات منشورة" value={data.matches.length} note="من المصادر المفتوحة"/><Kpi icon={<Target/>} label="ملخص المواجهات" value={`${data.aggregate?.winsA||0} - ${data.aggregate?.draws||0} - ${data.aggregate?.winsB||0}`} note="فوز A - تعادل - فوز B"/><Kpi icon={<Clock3/>} label="النطاق" value="H2H" note="سجل منشور فقط"/></div><div className="list">{data.matches.slice(0,10).map((m:any,i:number)=><div className="card fixture" key={i}><div className="fixture-date">{formatDate(m.startTimeUtc)}</div><div className="fixture-teams"><strong>{m.homeTeam} × {m.awayTeam}</strong><span>{m.competitionLabel||m.competition}</span></div><div className="fixture-score">{m.homeScore} - {m.awayScore}</div></div>)}</div></>:<div className="empty">لا توجد مواجهات منشورة كافية بين الفريقين</div>}
function Timeline({events}:any){return events?.length?<div className="list">{events.map((e:any,i:number)=><div className="fixture" key={i}><div className="fixture-date">{e.minute||e.clock||`${i+1}'`}</div><div className="fixture-teams"><strong>{e.player||e.text||e.type||"حدث"}</strong><span>{e.team||e.detail||""}</span></div><div className="fixture-score">•</div></div>)}</div>:<div className="empty">لا توجد أحداث منشورة حتى الآن</div>}
function Stats({stats}:any){const entries=Object.entries(stats||{});return entries.length?<div className="grid grid-3">{entries.slice(0,12).map(([k,v]:any)=><div className="card kpi" key={k}><div className="kpi-label">{k}</div><div className="kpi-value" style={{fontSize:24}}>{String(v)}</div></div>)}</div>:<div className="empty">الإحصائيات غير متاحة من المصدر لهذه المباراة</div>}
export default App;
